spring: 
  profiles:
    active:
    - dev
server: 
  port: 80
  context-path: /
spring:
  profiles: dev
  application: 
    name: user-consumer80

eureka: 
  client: 
  	#false 由于注册中心的职责就是维护服务实例，它并不需要去检索服务，所以也设置为false
    register-with-eureka: false 
    service-url: 
      defaultZone: http://localhost:2004/eureka/
---
server: 
  port: 80
  context-path: /
  
spring:
  profiles: test
  application: 
    name: user-consumer80
  
eureka: 
  client: 
  	#false 由于注册中心的职责就是维护服务实例，它并不需要去检索服务，所以也设置为false
    register-with-eureka: false 
    service-url: 
      defaultZone: http://localhost:2004/eureka/
